name:                P4-Bims-Haskell
version:             0.1.0.0
github:              "Spidercoder/P4-Bims"
license:             BSD3
author:              Group d406f19 - Aalborg University
maintainer:          Group d406f19 - Aalborg University
copyright:           Group d406f19 - Aalborg University 2019

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Spidercoder/P4-Bims#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  P4-Bims-Haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - P4-Bims-Haskell

tests:
  P4-Bims-Haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - P4-Bims-Haskell
